version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0

    working_directory: ~/usd-please

    # branches:
    #   ignore:
    #     - develop
    #     - /feature-.*/

    steps:
      - checkout

      # - run:
      #     name: "Node version check"
      #     command: "node -v && npm -v"

      - run:
          name: Dependency installation
          command: npm i

      - run:
          name: Testing
          command: npm run test
        
      - run:
          name: Formatting
          command: npm run format
