version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
      - image: node:8.0

    working_directory: ~/usd-please

    # branches:
    #   ignore:
    #     - develop
    #     - /feature-.*/

    steps:
      - checkout

      - run:
          name: "Node version check"
          command: "node -v && npm -v"

      - run:
          name: "Dependency installation"
          command: "sudo npm i"

      - run:
          name: "Formatting/testing"
          command: "sudo npm run test && sudo npm run format"
